refactor: set purchase limit & mint in pre-order by participant
thematters/traveloggers-contracts pull request #47
Opened 2021-10-25 14:40 UTC by Carolusian

- purchase limit per participant is hard coded to 5
- add query functions of NFTs minted in pre-order
- add field in participant to store the number of NFTs minted to the participent
- ~~use integer (floor) division if the paid amount is more than the price and less then price x n (2..n)~~

2021-10-25 17:20 UTC, guoliu requested changes
Left a small comment, else looks good!

2021-10-25 17:20 UTC, guoliu commented on contracts/PreOrder.sol
> +            _preOrderIndex.current() < preOrderParticipantsAllowed,
Since one participant can order more than one NFT, this check and limitation should be changed to total number of NFT ordered (maybe via `_preOrderMintIndex`?)

2021-10-26 03:05 UTC, Carolusian commented on contracts/PreOrder.sol
> +            _preOrderIndex.current() < preOrderParticipantsAllowed,
@guoliu moved the checking to apply to new participants only. please check.

2021-10-26 03:18 UTC, robertu7 requested changes

2021-10-26 03:18 UTC, robertu7 commented on contracts/PreOrder.sol
> +    uint256 public preOrderLimit = 5;
use `constant` if it's unchanged?

2021-10-26 03:36 UTC, Carolusian commented on contracts/PreOrder.sol
> +    uint256 public preOrderLimit = 5;
@robertu7 updated to constant, pls check.

2021-10-26 03:58 UTC, robertu7 commented on contracts/PreOrder.sol
> +        uint256 numNFT = msg.value.div(
The cost of SafeMath could be saved if `preOrder` have an argument to passing quantity, then we multiply it with `preOrderMinAmount`?

```solidity
totalAmount = preOrderMinAmount * quantity

require(msg.value > totalAmount, "....")
```

2021-10-26 17:00 UTC, Carolusian commented on contracts/PreOrder.sol
> +        uint256 numNFT = msg.value.div(
Updated. But it seems the gas used was not reduced. 

Use SafeMath division:
<img width="510" alt="safedivision" src="https://user-images.githubusercontent.com/556963/138926211-77b94295-69b7-45c8-9d8a-aa52f4f9ea84.png">

Use explicit quantity argument:
<img width="489" alt="Screenshot 2021-10-27 at 12 53 31 AM" src="https://user-images.githubusercontent.com/556963/138926348-b778938a-4502-43b1-b13e-ae23e2658beb.png">

2021-10-26 17:41 UTC, Carolusian commented on contracts/PreOrder.sol
> +            _preOrderIndex.current() < preOrderParticipantsAllowed,
@guoliu switched from participants checking to pre-order supply checking.

2021-10-26 21:46 UTC, guoliu approved these changes
🌿

2021-10-27 07:16 UTC, robertu7 approved these changes
GO

2021-10-27 07:29 UTC, merged